import { Navbar } from "@/components/navbar"
import { Hero } from "@/components/hero"
import { TechnicalPanel } from "@/components/technical-panel"
import { ProofFeatures } from "@/components/proof-features"
import { ApiSection } from "@/components/api-section"
import { DepthScale } from "@/components/depth-scale"
import { Customers } from "@/components/customers"
import { CtaFooter } from "@/components/cta-footer"
import { ParallaxBackground } from "@/components/parallax-background"
export default function Page(){return <main className="relative min-h-screen bg-background"><ParallaxBackground/><div className="relative z-10"><Navbar/><Hero/><TechnicalPanel/><ProofFeatures/><ApiSection/><DepthScale/><Customers/><CtaFooter/></div></main>}
