"use client"

import { useEffect,useMemo,useState } from "react"
import { BarChart3,Bell,Bookmark,CalendarDays,CircleDollarSign,Clock,Eye,Inbox,LayoutDashboard,LogIn,Mail,Menu,Plus,Search,Settings,Star,Users,X } from "lucide-react"
import type { AgendaEvent,Charge,Client,CrmOverview,Lead,TrafficOverview } from "@/lib/db"

type View="overview"|"messages"|"clients"|"finance"|"agenda"|"settings"
const emptyAnalytics:TrafficOverview={total:0,today:0,uniqueSessions:0,sources:[],pages:[],devices:[],hours:[]}
const emptyCrm:CrmOverview={clients:0,activeClients:0,mrr:0,pending:0,overdue:0,dueSoon:0,meetings:0}

export function AdminDashboard(){
  const [leads,setLeads]=useState<Lead[]|null>(null),[clients,setClients]=useState<Client[]>([]),[charges,setCharges]=useState<Charge[]>([]),[events,setEvents]=useState<AgendaEvent[]>([]),[analytics,setAnalytics]=useState(emptyAnalytics),[crm,setCrm]=useState(emptyCrm)
  const [password,setPassword]=useState(""),[error,setError]=useState(""),[query,setQuery]=useState(""),[selected,setSelected]=useState<Lead|null>(null)
  const [view,setView]=useState<View>("overview"),[menu,setMenu]=useState(false),[clientForm,setClientForm]=useState<Partial<Client>|null>(null),[chargeForm,setChargeForm]=useState<Partial<Charge>|null>(null),[eventForm,setEventForm]=useState<Partial<AgendaEvent>|null>(null),[setup,setSetup]=useState(false)
  async function load(){const [lr,ar,cr,fr,er,or]=await Promise.all([fetch("/api/admin/leads"),fetch("/api/admin/analytics"),fetch("/api/admin/clients"),fetch("/api/admin/charges"),fetch("/api/admin/agenda"),fetch("/api/admin/crm-overview")]);if(!lr.ok){setLeads(null);return}const ld=await lr.json();setLeads(ld.leads);setSetup(!!ld.setup);if(ar.ok)setAnalytics(await ar.json());if(cr.ok)setClients((await cr.json()).clients||[]);if(fr.ok)setCharges((await fr.json()).charges||[]);if(er.ok)setEvents((await er.json()).events||[]);if(or.ok)setCrm(await or.json())}
  useEffect(()=>{load()},[])
  async function login(e:React.FormEvent){e.preventDefault();const r=await fetch("/api/admin/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({password})});if(r.ok)load();else setError("Senha inválida ou não configurada.")}
  async function updateLead(id:number,data:{status?:string;important?:boolean}){await fetch("/api/admin/leads",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,...data})});await load();setSelected(s=>s?.id===id?{...s,...data}:s)}
  async function saveForm(e:React.FormEvent,kind:"clients"|"charges"|"agenda",data:object,close:()=>void){e.preventDefault();const r=await fetch(`/api/admin/${kind}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(data)});if(r.ok){close();load()}else setError((await r.json()).error||"Não foi possível salvar")}
  const filtered=useMemo(()=>leads?.filter(x=>(x.name+x.email+(x.company||"")+x.message).toLowerCase().includes(query.toLowerCase()))||[],[leads,query])
  if(!leads)return <Login password={password} setPassword={setPassword} error={error} submit={login}/>
  const unread=leads.filter(x=>x.status==="new").length,important=leads.filter(x=>x.important).length,later=leads.filter(x=>x.status==="later").length
  return <div className="min-h-screen bg-[#17171d] p-2 text-white sm:p-5"><div className="mx-auto flex min-h-[calc(100vh-2.5rem)] max-w-[1560px] overflow-hidden rounded-[26px] border border-white/10 bg-[#080a0e] shadow-2xl">
    <Sidebar view={view} setView={v=>{setView(v);setMenu(false)}} unread={unread} open={menu}/>
    <main className="min-w-0 flex-1 overflow-hidden"><Topbar query={query} setQuery={setQuery} menu={()=>setMenu(!menu)} unread={unread}/><div className="h-[calc(100vh-6.5rem)] overflow-y-auto p-4 sm:p-7 lg:p-9">
      {setup&&<div className="mb-6 rounded-xl border border-yellow-400/25 bg-yellow-400/10 p-4 text-sm text-yellow-200">Conecte o Neon à Vercel e configure DATABASE_URL para ativar contatos e métricas.</div>}
      {view==="overview"&&<Overview analytics={analytics} crm={crm} leads={leads} unread={unread} important={important} openMessages={()=>setView("messages")}/>} 
      {view==="messages"&&<Messages leads={filtered} selected={selected} setSelected={x=>{setSelected(x);if(x?.status==="new")updateLead(x.id,{status:"read"})}} updateLead={updateLead} important={important} later={later}/>} 
      {view==="clients"&&<ClientsView clients={clients} edit={setClientForm}/>} 
      {view==="finance"&&<FinanceView charges={charges} clients={clients} edit={setChargeForm} quickPay={async c=>{await fetch("/api/admin/charges",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...c,clientId:c.client_id,dueDate:c.due_date,status:"paid"})});load()}}/>} 
      {view==="agenda"&&<AgendaView events={events} clients={clients} edit={setEventForm}/>} 
      {view==="settings"&&<SettingsView/>}
    </div></main>
    {selected&&<MessageDrawer lead={selected} close={()=>setSelected(null)} update={updateLead}/>} 
    {clientForm&&<ClientModal data={clientForm} setData={setClientForm} close={()=>setClientForm(null)} submit={e=>saveForm(e,"clients",clientForm,()=>setClientForm(null))}/>} 
    {chargeForm&&<ChargeModal data={chargeForm} clients={clients} setData={setChargeForm} close={()=>setChargeForm(null)} submit={e=>saveForm(e,"charges",{...chargeForm,clientId:chargeForm.client_id,dueDate:chargeForm.due_date},()=>setChargeForm(null))}/>} 
    {eventForm&&<EventModal data={eventForm} clients={clients} setData={setEventForm} close={()=>setEventForm(null)} submit={e=>saveForm(e,"agenda",{...eventForm,clientId:eventForm.client_id,startsAt:eventForm.starts_at,eventType:eventForm.event_type},()=>setEventForm(null))}/>} 
  </div></div>
}

function Login({password,setPassword,error,submit}:{password:string;setPassword:(v:string)=>void;error:string;submit:(e:React.FormEvent)=>void}){return <div className="flex min-h-screen items-center justify-center bg-[#080a0e] px-4"><form onSubmit={submit} className="w-full max-w-md rounded-3xl border border-white/10 bg-[#0e1118] p-8 shadow-2xl"><div className="mb-8 flex h-12 w-12 items-center justify-center rounded-xl bg-[#4169E1] shadow-[0_0_30px_rgba(65,105,225,.45)]"><LogIn/></div><p className="font-mono text-xs text-[#6C8EFF]">BAWERK / ADMIN</p><h1 className="mt-3 text-3xl font-semibold">Bem-vindo de volta</h1><p className="mt-2 text-sm text-zinc-500">Sua central de clientes, cobranças, agenda e contatos.</p><input value={password} onChange={e=>setPassword(e.target.value)} type="password" placeholder="Senha administrativa" className="mt-7 w-full rounded-xl border border-white/10 bg-black/30 px-4 py-3 outline-none focus:border-[#4169E1]"/><button className="mt-4 w-full rounded-xl bg-[#4169E1] px-4 py-3 font-medium transition hover:bg-[#5579e7]">Entrar</button>{error&&<p className="mt-4 text-sm text-red-400">{error}</p>}</form></div>}
function Sidebar({view,setView,unread,open}:{view:View;setView:(v:View)=>void;unread:number;open:boolean}){const items:[View,typeof LayoutDashboard,string][]=[["overview",LayoutDashboard,"Visão geral"],["messages",Inbox,"Mensagens"],["clients",Users,"Clientes"],["finance",CircleDollarSign,"Financeiro"],["agenda",CalendarDays,"Agenda"],["settings",Settings,"Configurações"]];return <aside className={`${open?"flex":"hidden"} fixed inset-y-2 left-2 z-40 w-64 flex-col rounded-l-[26px] border-r border-white/10 bg-[#080a0e] p-5 lg:static lg:flex lg:w-64`}><div className="flex items-center gap-3 border-b border-white/10 pb-6"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#4169E1] font-mono font-bold shadow-[0_0_22px_rgba(65,105,225,.45)]">BW</div><div><p className="font-semibold">BAWERK</p><p className="text-[11px] text-zinc-500">Gestão interna</p></div></div><nav className="mt-7 space-y-2">{items.map(([id,Icon,label])=><button key={id} onClick={()=>setView(id)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-sm transition ${view===id?"bg-gradient-to-r from-[#4169E1] to-[#2b54cf] text-white shadow-[0_8px_24px_rgba(65,105,225,.22)]":"text-zinc-500 hover:bg-white/5 hover:text-white"}`}><Icon className="h-4 w-4"/><span>{label}</span>{id==="messages"&&unread>0&&<b className="ml-auto rounded-full bg-white/15 px-2 py-0.5 text-[10px]">{unread}</b>}</button>)}</nav><div className="mt-auto rounded-2xl border border-white/10 bg-white/[.025] p-4"><p className="text-xs text-zinc-500">Acesso exclusivo</p><div className="mt-2 flex items-center gap-2 text-sm"><i className="h-2 w-2 rounded-full bg-emerald-400"/>Administrador BAWERK</div></div></aside>}
function Topbar({query,setQuery,menu,unread}:{query:string;setQuery:(v:string)=>void;menu:()=>void;unread:number}){return <header className="flex h-20 items-center gap-3 border-b border-white/10 px-4 sm:px-7"><button onClick={menu} className="rounded-lg p-2 hover:bg-white/5 lg:hidden"><Menu/></button><label className="flex max-w-xl flex-1 items-center gap-3 rounded-xl border border-white/5 bg-[#11141b] px-4 py-3"><Search className="h-4 w-4 text-zinc-500"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar mensagens e clientes" className="min-w-0 flex-1 bg-transparent text-sm outline-none"/></label><button className="relative ml-auto rounded-xl border border-white/5 bg-[#11141b] p-3"><Bell className="h-4 w-4"/>{unread>0&&<i className="absolute right-2 top-2 h-2 w-2 rounded-full bg-red-500"/>}</button><div className="hidden items-center gap-3 sm:flex"><div className="flex h-10 w-10 items-center justify-center rounded-full bg-[#4169E1]/20 font-semibold text-[#8ca5ff]">A</div><div><p className="text-sm">Administrador</p><p className="text-[11px] text-zinc-500">BAWERK Solutions</p></div></div></header>}

function Overview({analytics,crm,leads,unread,important,openMessages}:{analytics:TrafficOverview;crm:CrmOverview;leads:Lead[];unread:number;important:number;openMessages:()=>void}){return <><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm text-[#6C8EFF]">Visão geral</p><h1 className="mt-1 text-3xl font-semibold">Dashboard</h1><p className="mt-2 text-sm text-zinc-500">Operação, clientes, receita e desempenho do site em um só lugar.</p></div><p className="rounded-xl border border-white/10 bg-white/[.025] px-4 py-2 text-xs text-zinc-400">Atualizado agora</p></div><div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric title="Receita recorrente" value={money(crm.mrr)} icon={CircleDollarSign} note={`${crm.activeClients} clientes ativos`}/><Metric title="Valores pendentes" value={money(crm.pending)} icon={Clock} note={`${crm.overdue} cobranças atrasadas`}/><Metric title="Vencem em 7 dias" value={crm.dueSoon} icon={CalendarDays} note={`${crm.meetings} compromissos próximos`}/><Metric title="Novas mensagens" value={unread} icon={Mail} note={`${leads.length} contatos no total`}/></div><div className="mt-5 grid gap-5 xl:grid-cols-[1.7fr_1fr]"><TrafficChart hours={analytics.hours}/><Ranking title="Origem dos acessos" rows={analytics.sources}/></div><div className="mt-5 grid gap-5 xl:grid-cols-[1.15fr_1fr]"><Recent leads={leads.slice(0,5)} open={openMessages}/><div className="grid gap-5 sm:grid-cols-2"><Ranking title="Páginas mais acessadas" rows={analytics.pages}/><Ranking title="Dispositivos" rows={analytics.devices}/></div></div></>}
function Metric({title,value,icon:Icon,note}:{title:string;value:number|string;icon:typeof Eye;note:string}){return <div className="rounded-2xl border border-white/10 bg-[#0e1118] p-5 transition hover:border-[#4169E1]/50"><div className="flex items-center justify-between"><p className="text-sm text-zinc-400">{title}</p><span className="rounded-xl bg-[#4169E1]/15 p-2 text-[#6C8EFF]"><Icon className="h-4 w-4"/></span></div><p className="mt-5 text-3xl font-semibold">{typeof value==="number"?value.toLocaleString("pt-BR"):value}</p><p className="mt-2 text-xs text-zinc-600">{note}</p></div>}
function TrafficChart({hours}:{hours:{label:string;value:number}[]}){const max=Math.max(1,...hours.map(x=>x.value));const points=hours.map((x,i)=>`${(i/(Math.max(1,hours.length-1)))*100},${92-(x.value/max)*72}`).join(" ");return <div className="rounded-2xl border border-white/10 bg-[#0e1118] p-5 sm:p-6"><div><h2 className="font-medium">Tráfego por horário</h2><p className="mt-1 text-xs text-zinc-500">Acessos registrados hoje</p></div><div className="mt-7 h-64 overflow-hidden rounded-xl bg-[linear-gradient(rgba(255,255,255,.035)_1px,transparent_1px)] bg-[size:100%_25%]"><svg viewBox="0 0 100 100" preserveAspectRatio="none" className="h-full w-full"><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#4169E1" stopOpacity=".65"/><stop offset="1" stopColor="#4169E1" stopOpacity="0"/></linearGradient></defs><polygon points={`0,100 ${points} 100,100`} fill="url(#area)"/><polyline points={points} fill="none" stroke="#6C8EFF" strokeWidth="1.1" vectorEffect="non-scaling-stroke"/></svg></div><div className="mt-3 flex justify-between text-[10px] text-zinc-600"><span>00:00</span><span>06:00</span><span>12:00</span><span>18:00</span><span>23:00</span></div></div>}
function Ranking({title,rows}:{title:string;rows:{label:string;value:number}[]}){const max=Math.max(1,...rows.map(x=>x.value));return <div className="rounded-2xl border border-white/10 bg-[#0e1118] p-5"><h2 className="font-medium">{title}</h2><div className="mt-5 space-y-4">{rows.length?rows.map(x=><div key={x.label}><div className="flex justify-between gap-3 text-xs"><span className="truncate text-zinc-400">{x.label}</span><b>{x.value}</b></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-white/5"><div className="h-full rounded-full bg-[#4169E1]" style={{width:`${Math.max(8,x.value/max*100)}%`}}/></div></div>):<p className="py-8 text-center text-xs text-zinc-600">Os dados aparecerão após novos acessos.</p>}</div></div>}
function Recent({leads,open}:{leads:Lead[];open:()=>void}){return <div className="rounded-2xl border border-white/10 bg-[#0e1118] p-5"><div className="flex items-center justify-between"><h2 className="font-medium">Contatos recentes</h2><button onClick={open} className="text-xs text-[#6C8EFF]">Ver todos</button></div><div className="mt-4 divide-y divide-white/5">{leads.map(x=><div className="flex items-center gap-3 py-3" key={x.id}><Avatar name={x.name}/><div className="min-w-0"><p className="truncate text-sm">{x.name}</p><p className="truncate text-xs text-zinc-500">{x.service||x.email}</p></div><Status value={x.status}/></div>)}{!leads.length&&<p className="py-8 text-center text-sm text-zinc-600">Nenhum contato ainda.</p>}</div></div>}

function Messages({leads,selected,setSelected,updateLead,important,later}:{leads:Lead[];selected:Lead|null;setSelected:(x:Lead|null)=>void;updateLead:(id:number,d:{status?:string;important?:boolean})=>void;important:number;later:number}){return <><div><p className="text-sm text-[#6C8EFF]">Central de contatos</p><h1 className="mt-1 text-3xl font-semibold">Mensagens</h1></div><div className="mt-6 flex flex-wrap gap-3"><Pill icon={Inbox} text={`${leads.length} mensagens`}/><Pill icon={Star} text={`${important} importantes`}/><Pill icon={Bookmark} text={`${later} para ver depois`}/></div><div className="mt-6 overflow-hidden rounded-2xl border border-white/10 bg-[#0e1118]"><div className="hidden grid-cols-[36px_1fr_1fr_150px_110px] gap-4 border-b border-white/10 px-5 py-4 text-xs text-zinc-600 sm:grid"><span/><span>Cliente</span><span>Assunto</span><span>Status</span><span>Data</span></div>{leads.map(x=><button key={x.id} onClick={()=>setSelected(x)} className={`grid w-full grid-cols-[32px_1fr_auto] items-center gap-3 border-b border-white/5 px-4 py-4 text-left transition hover:bg-white/[.025] sm:grid-cols-[36px_1fr_1fr_150px_110px] sm:px-5 ${x.status==="new"?"bg-[#4169E1]/[.035]":""}`}><Star onClick={e=>{e.stopPropagation();updateLead(x.id,{important:!x.important})}} className={`h-4 w-4 ${x.important?"fill-yellow-400 text-yellow-400":"text-zinc-700"}`}/><div className="min-w-0"><p className="truncate text-sm font-medium">{x.name}</p><p className="truncate text-xs text-zinc-600">{x.email}</p></div><div className="hidden min-w-0 sm:block"><p className="truncate text-sm text-zinc-400">{x.service||"Novo contato"}</p><p className="truncate text-xs text-zinc-600">{x.message}</p></div><Status value={x.status}/><span className="hidden text-xs text-zinc-600 sm:block">{new Date(x.created_at).toLocaleDateString("pt-BR")}</span></button>)}{!leads.length&&<p className="p-12 text-center text-zinc-600">Nenhuma mensagem encontrada.</p>}</div></>}
function MessageDrawer({lead,close,update}:{lead:Lead;close:()=>void;update:(id:number,d:{status?:string;important?:boolean})=>void}){return <div className="fixed inset-0 z-50 flex justify-end bg-black/70 backdrop-blur-sm" onClick={close}><article onClick={e=>e.stopPropagation()} className="h-full w-full max-w-2xl overflow-y-auto border-l border-white/10 bg-[#0b0e14] p-6 sm:p-9"><div className="flex items-center justify-between"><button onClick={close} className="text-sm text-zinc-500">Fechar</button><button onClick={()=>update(lead.id,{important:!lead.important})} className={`rounded-xl border p-3 ${lead.important?"border-yellow-400/30 bg-yellow-400/10 text-yellow-400":"border-white/10 text-zinc-500"}`}><Star className={`h-4 w-4 ${lead.important?"fill-current":""}`}/></button></div><div className="mt-9 flex items-center gap-4"><Avatar name={lead.name} big/><div><h2 className="text-2xl font-semibold">{lead.name}</h2><a href={`mailto:${lead.email}`} className="text-sm text-[#6C8EFF]">{lead.email}</a></div></div><div className="mt-8 grid gap-3 rounded-2xl border border-white/10 bg-white/[.02] p-5 text-sm sm:grid-cols-2"><p><span className="text-zinc-600">Telefone</span><br/>{lead.phone||"—"}</p><p><span className="text-zinc-600">Empresa</span><br/>{lead.company||"—"}</p><p><span className="text-zinc-600">Serviço</span><br/>{lead.service||"—"}</p><p><span className="text-zinc-600">Investimento</span><br/>{lead.budget||"—"}</p></div><div className="mt-7"><p className="text-xs uppercase tracking-widest text-zinc-600">Mensagem</p><p className="mt-4 whitespace-pre-wrap leading-7 text-zinc-300">{lead.message}</p></div><div className="mt-9 flex flex-wrap gap-3"><button onClick={()=>update(lead.id,{status:"responded"})} className="rounded-xl bg-[#4169E1] px-5 py-3 text-sm">Marcar como respondida</button><button onClick={()=>update(lead.id,{status:"later"})} className="rounded-xl border border-white/10 px-5 py-3 text-sm">Ver depois</button><button onClick={()=>update(lead.id,{status:"archived"})} className="rounded-xl border border-white/10 px-5 py-3 text-sm text-zinc-500">Arquivar</button></div></article></div>}

function PageTitle({eyebrow,title,description,action}:{eyebrow:string;title:string;description:string;action:()=>void}){return <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm text-[#6C8EFF]">{eyebrow}</p><h1 className="mt-1 text-3xl font-semibold">{title}</h1><p className="mt-2 text-sm text-zinc-500">{description}</p></div><button onClick={action} className="flex items-center gap-2 rounded-xl bg-[#4169E1] px-5 py-3 text-sm"><Plus className="h-4 w-4"/>Adicionar</button></div>}
function ClientsView({clients,edit}:{clients:Client[];edit:(u:Partial<Client>)=>void}){return <><PageTitle eyebrow="CRM interno" title="Clientes" description="Cadastre e acompanhe seus clientes sem criar acesso para eles." action={()=>edit({status:"active"})}/><div className="mt-7 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{clients.map(c=><button onClick={()=>edit(c)} key={c.id} className="rounded-2xl border border-white/10 bg-[#0e1118] p-5 text-left transition hover:border-[#4169E1]/50"><div className="flex items-center gap-4"><Avatar name={c.name} big/><div className="min-w-0"><p className="truncate font-medium">{c.name}</p><p className="truncate text-xs text-zinc-500">{c.company||c.email||"Cliente BAWERK"}</p></div><ClientStatus value={c.status}/></div><div className="mt-5 grid grid-cols-2 gap-3 border-t border-white/5 pt-4 text-xs text-zinc-500"><span>{c.phone||"Sem telefone"}</span><span className="truncate text-right">{c.email||"Sem e-mail"}</span></div></button>)}{!clients.length&&<Empty text="Nenhum cliente cadastrado. Use Adicionar para começar."/>}</div></>}
function FinanceView({charges,clients,edit,quickPay}:{charges:Charge[];clients:Client[];edit:(u:Partial<Charge>)=>void;quickPay:(c:Charge)=>void}){return <><PageTitle eyebrow="Controle financeiro" title="Cobranças e vencimentos" description="Mensalidades, renovações e pagamentos de cada cliente." action={()=>edit({status:"pending",recurrence:"monthly",due_date:new Date().toISOString().slice(0,10),client_id:clients[0]?.id})}/><div className="mt-7 overflow-hidden rounded-2xl border border-white/10 bg-[#0e1118]"><div className="hidden grid-cols-[1.2fr_1fr_130px_130px_120px] gap-4 border-b border-white/10 px-5 py-4 text-xs text-zinc-600 md:grid"><span>Cliente</span><span>Serviço</span><span>Valor</span><span>Vencimento</span><span>Status</span></div>{charges.map(c=><div key={c.id} className="grid gap-3 border-b border-white/5 px-5 py-4 md:grid-cols-[1.2fr_1fr_130px_130px_120px] md:items-center"><button onClick={()=>edit(c)} className="text-left text-sm font-medium">{c.client_name}</button><span className="text-sm text-zinc-400">{c.title}</span><b className="text-sm">{money(Number(c.amount))}</b><span className="text-xs text-zinc-500">{date(c.due_date)}</span><div className="flex items-center gap-2"><PaymentStatus value={c.status}/>{c.status!=="paid"&&<button onClick={()=>quickPay(c)} title="Marcar como pago" className="rounded-lg bg-emerald-400/10 px-2 py-1 text-[10px] text-emerald-300">Pagar</button>}</div></div>)}{!charges.length&&<Empty text={clients.length?"Nenhuma cobrança cadastrada.":"Cadastre um cliente antes de adicionar cobranças."}/>}</div></>}
function AgendaView({events,clients,edit}:{events:AgendaEvent[];clients:Client[];edit:(u:Partial<AgendaEvent>)=>void}){return <><PageTitle eyebrow="Organização" title="Agenda" description="Reuniões, tarefas e prazos ligados aos seus clientes." action={()=>edit({status:"scheduled",event_type:"meeting",starts_at:new Date(Date.now()+86400000).toISOString().slice(0,16),client_id:clients[0]?.id})}/><div className="mt-7 grid gap-4 xl:grid-cols-2">{events.map(e=><button onClick={()=>edit(e)} key={e.id} className="flex items-center gap-4 rounded-2xl border border-white/10 bg-[#0e1118] p-5 text-left transition hover:border-[#4169E1]/50"><span className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl bg-[#4169E1]/15 text-[#6C8EFF]"><CalendarDays/></span><div className="min-w-0"><p className="font-medium">{e.title}</p><p className="mt-1 truncate text-xs text-zinc-500">{e.client_name||"Compromisso interno"} · {dateTime(e.starts_at)}</p></div><EventStatus value={e.status}/></button>)}{!events.length&&<Empty text="Sua agenda está livre. Adicione uma reunião, tarefa ou prazo."/>}</div></>}
function Modal({title,close,submit,children}:{title:string;close:()=>void;submit:(e:React.FormEvent)=>void;children:React.ReactNode}){return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/75 p-4 backdrop-blur-sm" onClick={close}><form onSubmit={submit} onClick={e=>e.stopPropagation()} className="max-h-[92vh] w-full max-w-xl overflow-y-auto rounded-3xl border border-white/10 bg-[#0e1118] p-6 sm:p-8"><div className="flex items-center justify-between"><h2 className="text-xl font-semibold">{title}</h2><button type="button" onClick={close}><X className="text-zinc-500"/></button></div><div className="mt-6 grid gap-4">{children}</div><button className="mt-6 w-full rounded-xl bg-[#4169E1] px-5 py-3">Salvar</button></form></div>}
function ClientModal({data,setData,close,submit}:{data:Partial<Client>;setData:(d:Partial<Client>)=>void;close:()=>void;submit:(e:React.FormEvent)=>void}){return <Modal title={data.id?"Editar cliente":"Novo cliente"} close={close} submit={submit}><Field label="Nome" value={data.name||""} change={v=>setData({...data,name:v})}/><Field label="Empresa" value={data.company||""} change={v=>setData({...data,company:v})} required={false}/><div className="grid gap-4 sm:grid-cols-2"><Field label="E-mail" value={data.email||""} change={v=>setData({...data,email:v})} type="email" required={false}/><Field label="Telefone" value={data.phone||""} change={v=>setData({...data,phone:v})} required={false}/></div><Select label="Status" value={data.status||"active"} change={v=>setData({...data,status:v})} options={[["active","Ativo"],["paused","Pausado"],["cancelled","Cancelado"]]}/><TextArea label="Observações" value={data.notes||""} change={v=>setData({...data,notes:v})}/></Modal>}
function ChargeModal({data,clients,setData,close,submit}:{data:Partial<Charge>;clients:Client[];setData:(d:Partial<Charge>)=>void;close:()=>void;submit:(e:React.FormEvent)=>void}){return <Modal title={data.id?"Editar cobrança":"Nova cobrança"} close={close} submit={submit}><Select label="Cliente" value={String(data.client_id||"")} change={v=>setData({...data,client_id:Number(v)})} options={clients.map(c=>[String(c.id),c.name])}/><Field label="Serviço ou cobrança" value={data.title||""} change={v=>setData({...data,title:v})}/><div className="grid gap-4 sm:grid-cols-2"><Field label="Valor (R$)" value={String(data.amount||"")} change={v=>setData({...data,amount:Number(v)})} type="number"/><Field label="Vencimento" value={String(data.due_date||"").slice(0,10)} change={v=>setData({...data,due_date:v})} type="date"/></div><div className="grid gap-4 sm:grid-cols-2"><Select label="Recorrência" value={data.recurrence||"monthly"} change={v=>setData({...data,recurrence:v})} options={[["monthly","Mensal"],["annual","Anual"],["once","Avulsa"]]}/><Select label="Status" value={data.status||"pending"} change={v=>setData({...data,status:v})} options={[["pending","Pendente"],["paid","Pago"],["overdue","Atrasado"],["paused","Pausado"],["cancelled","Cancelado"]]}/></div><TextArea label="Observações" value={data.notes||""} change={v=>setData({...data,notes:v})}/></Modal>}
function EventModal({data,clients,setData,close,submit}:{data:Partial<AgendaEvent>;clients:Client[];setData:(d:Partial<AgendaEvent>)=>void;close:()=>void;submit:(e:React.FormEvent)=>void}){return <Modal title={data.id?"Editar compromisso":"Novo compromisso"} close={close} submit={submit}><Field label="Título" value={data.title||""} change={v=>setData({...data,title:v})}/><Select label="Cliente (opcional)" value={String(data.client_id||"")} change={v=>setData({...data,client_id:v?Number(v):undefined})} options={[["","Nenhum"],...clients.map(c=>[String(c.id),c.name])]}/><Field label="Data e horário" value={String(data.starts_at||"").slice(0,16)} change={v=>setData({...data,starts_at:v})} type="datetime-local"/><div className="grid gap-4 sm:grid-cols-2"><Select label="Tipo" value={data.event_type||"meeting"} change={v=>setData({...data,event_type:v})} options={[["meeting","Reunião"],["task","Tarefa"],["deadline","Prazo"]]}/><Select label="Status" value={data.status||"scheduled"} change={v=>setData({...data,status:v})} options={[["scheduled","Agendado"],["done","Concluído"],["cancelled","Cancelado"]]}/></div><TextArea label="Observações" value={data.notes||""} change={v=>setData({...data,notes:v})}/></Modal>}
function SettingsView(){return <div><p className="text-sm text-[#6C8EFF]">Sistema</p><h1 className="mt-1 text-3xl font-semibold">Configurações</h1><div className="mt-7 grid max-w-3xl gap-4"><div className="rounded-2xl border border-white/10 bg-[#0e1118] p-6"><h2 className="font-medium">Acesso exclusivo</h2><p className="mt-2 text-sm leading-6 text-zinc-500">Existe somente uma conta administrativa: a sua. A senha e o segredo de sessão são definidos por ADMIN_PASSWORD e ADMIN_SECRET na Vercel.</p></div><div className="rounded-2xl border border-white/10 bg-[#0e1118] p-6"><h2 className="font-medium">Dados da operação</h2><p className="mt-2 text-sm leading-6 text-zinc-500">Clientes, cobranças, agenda, contatos e métricas ficam armazenados no banco Neon conectado ao projeto.</p></div><div className="rounded-2xl border border-white/10 bg-[#0e1118] p-6"><h2 className="font-medium">Google Analytics</h2><p className="mt-2 text-sm leading-6 text-zinc-500">A medição interna já registra origem, páginas e dispositivos. Uma propriedade do Google Analytics pode ser conectada futuramente para relatórios complementares.</p></div></div></div>}

function Avatar({name,big=false}:{name:string;big?:boolean}){return <span className={`flex shrink-0 items-center justify-center rounded-full bg-gradient-to-br from-[#4169E1] to-[#223b91] font-semibold ${big?"h-14 w-14 text-lg":"h-10 w-10 text-sm"}`}>{name.split(" ").slice(0,2).map(x=>x[0]).join("").toUpperCase()}</span>}
function Status({value}:{value:string}){const map:Record<string,[string,string]>={new:["Nova","bg-[#4169E1]/15 text-[#8ca5ff]"],read:["Lida","bg-white/5 text-zinc-400"],later:["Ver depois","bg-amber-400/10 text-amber-300"],responded:["Respondida","bg-emerald-400/10 text-emerald-300"],archived:["Arquivada","bg-zinc-800 text-zinc-500"]};const [label,style]=map[value]||map.read;return <span className={`ml-auto w-fit rounded-full px-2.5 py-1 text-[10px] ${style}`}>{label}</span>}
function Pill({icon:Icon,text}:{icon:typeof Inbox;text:string}){return <span className="flex items-center gap-2 rounded-xl border border-white/10 bg-white/[.025] px-4 py-2 text-xs text-zinc-400"><Icon className="h-3.5 w-3.5 text-[#6C8EFF]"/>{text}</span>}
function Field({label,value,change,type="text",required=true}:{label:string;value:string;change:(v:string)=>void;type?:string;required?:boolean}){return <label className="text-sm text-zinc-400">{label}<input required={required} type={type} value={value} onChange={e=>change(e.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-black/30 px-4 py-3 text-white outline-none focus:border-[#4169E1]"/></label>}
function TextArea({label,value,change}:{label:string;value:string;change:(v:string)=>void}){return <label className="text-sm text-zinc-400">{label}<textarea value={value} onChange={e=>change(e.target.value)} rows={3} className="mt-2 w-full resize-none rounded-xl border border-white/10 bg-black/30 px-4 py-3 text-white outline-none focus:border-[#4169E1]"/></label>}
function Select({label,value,change,options}:{label:string;value:string;change:(v:string)=>void;options:string[][]}){return <label className="text-sm text-zinc-400">{label}<select required={options[0]?.[0]!==""} value={value} onChange={e=>change(e.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-[#090b10] px-4 py-3 text-white outline-none focus:border-[#4169E1]">{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>}
function Empty({text}:{text:string}){return <div className="col-span-full p-12 text-center text-sm text-zinc-600">{text}</div>}
function ClientStatus({value}:{value:string}){const m:Record<string,[string,string]>={active:["Ativo","bg-emerald-400/10 text-emerald-300"],paused:["Pausado","bg-amber-400/10 text-amber-300"],cancelled:["Cancelado","bg-zinc-800 text-zinc-500"]};const [l,s]=m[value]||m.active;return <span className={`ml-auto rounded-full px-2.5 py-1 text-[10px] ${s}`}>{l}</span>}
function PaymentStatus({value}:{value:string}){const m:Record<string,[string,string]>={pending:["Pendente","bg-amber-400/10 text-amber-300"],paid:["Pago","bg-emerald-400/10 text-emerald-300"],overdue:["Atrasado","bg-red-400/10 text-red-300"],paused:["Pausado","bg-zinc-700/50 text-zinc-400"],cancelled:["Cancelado","bg-zinc-800 text-zinc-600"]};const [l,s]=m[value]||m.pending;return <span className={`rounded-full px-2.5 py-1 text-[10px] ${s}`}>{l}</span>}
function EventStatus({value}:{value:string}){const m:Record<string,[string,string]>={scheduled:["Agendado","bg-[#4169E1]/15 text-[#8ca5ff]"],done:["Concluído","bg-emerald-400/10 text-emerald-300"],cancelled:["Cancelado","bg-zinc-800 text-zinc-500"]};const [l,s]=m[value]||m.scheduled;return <span className={`ml-auto rounded-full px-2.5 py-1 text-[10px] ${s}`}>{l}</span>}
function money(v:number){return v.toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}
function date(v:string){return new Date(v.includes("T")?v:`${v}T12:00:00`).toLocaleDateString("pt-BR")}
function dateTime(v:string){return new Date(v).toLocaleString("pt-BR",{dateStyle:"short",timeStyle:"short"})}
