"use client"

import { useEffect,useMemo,useState } from "react"
import { BarChart3,Bell,Bookmark,ChevronRight,Clock,Eye,Inbox,LayoutDashboard,LogIn,Mail,Menu,Search,Settings,Star,Users,X } from "lucide-react"
import type { AdminUser,Lead,TrafficOverview } from "@/lib/db"

type View="overview"|"messages"|"users"|"settings"
const emptyAnalytics:TrafficOverview={total:0,today:0,uniqueSessions:0,sources:[],pages:[],devices:[],hours:[]}

export function AdminDashboard(){
  const [leads,setLeads]=useState<Lead[]|null>(null),[users,setUsers]=useState<AdminUser[]>([]),[analytics,setAnalytics]=useState(emptyAnalytics)
  const [password,setPassword]=useState(""),[error,setError]=useState(""),[query,setQuery]=useState(""),[selected,setSelected]=useState<Lead|null>(null)
  const [view,setView]=useState<View>("overview"),[menu,setMenu]=useState(false),[userForm,setUserForm]=useState<Partial<AdminUser>|null>(null),[setup,setSetup]=useState(false)
  async function load(){const [lr,ar,ur]=await Promise.all([fetch("/api/admin/leads"),fetch("/api/admin/analytics"),fetch("/api/admin/users")]);if(!lr.ok){setLeads(null);return}const ld=await lr.json();setLeads(ld.leads);setSetup(!!ld.setup);if(ar.ok)setAnalytics(await ar.json());if(ur.ok)setUsers((await ur.json()).users||[])}
  useEffect(()=>{load()},[])
  async function login(e:React.FormEvent){e.preventDefault();const r=await fetch("/api/admin/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({password})});if(r.ok)load();else setError("Senha inválida ou não configurada.")}
  async function updateLead(id:number,data:{status?:string;important?:boolean}){await fetch("/api/admin/leads",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,...data})});await load();setSelected(s=>s?.id===id?{...s,...data}:s)}
  async function saveUser(e:React.FormEvent){e.preventDefault();const r=await fetch("/api/admin/users",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id:userForm?.id,name:userForm?.name,email:userForm?.email,role:userForm?.role||"Atendimento",avatarUrl:userForm?.avatar_url,status:userForm?.status||"active"})});if(r.ok){setUserForm(null);load()}}
  const filtered=useMemo(()=>leads?.filter(x=>(x.name+x.email+(x.company||"")+x.message).toLowerCase().includes(query.toLowerCase()))||[],[leads,query])
  if(!leads)return <Login password={password} setPassword={setPassword} error={error} submit={login}/>
  const unread=leads.filter(x=>x.status==="new").length,important=leads.filter(x=>x.important).length,later=leads.filter(x=>x.status==="later").length
  return <div className="min-h-screen bg-[#17171d] p-2 text-white sm:p-5"><div className="mx-auto flex min-h-[calc(100vh-2.5rem)] max-w-[1560px] overflow-hidden rounded-[26px] border border-white/10 bg-[#080a0e] shadow-2xl">
    <Sidebar view={view} setView={v=>{setView(v);setMenu(false)}} unread={unread} open={menu}/>
    <main className="min-w-0 flex-1 overflow-hidden"><Topbar query={query} setQuery={setQuery} menu={()=>setMenu(!menu)} unread={unread}/><div className="h-[calc(100vh-6.5rem)] overflow-y-auto p-4 sm:p-7 lg:p-9">
      {setup&&<div className="mb-6 rounded-xl border border-yellow-400/25 bg-yellow-400/10 p-4 text-sm text-yellow-200">Conecte o Neon à Vercel e configure DATABASE_URL para ativar contatos e métricas.</div>}
      {view==="overview"&&<Overview analytics={analytics} leads={leads} unread={unread} important={important} openMessages={()=>setView("messages")}/>} 
      {view==="messages"&&<Messages leads={filtered} selected={selected} setSelected={x=>{setSelected(x);if(x?.status==="new")updateLead(x.id,{status:"read"})}} updateLead={updateLead} important={important} later={later}/>} 
      {view==="users"&&<UsersView users={users} edit={setUserForm}/>} 
      {view==="settings"&&<SettingsView/>}
    </div></main>
    {selected&&<MessageDrawer lead={selected} close={()=>setSelected(null)} update={updateLead}/>} 
    {userForm&&<UserModal data={userForm} setData={setUserForm} close={()=>setUserForm(null)} submit={saveUser}/>} 
  </div></div>
}

function Login({password,setPassword,error,submit}:{password:string;setPassword:(v:string)=>void;error:string;submit:(e:React.FormEvent)=>void}){return <div className="flex min-h-screen items-center justify-center bg-[#080a0e] px-4"><form onSubmit={submit} className="w-full max-w-md rounded-3xl border border-white/10 bg-[#0e1118] p-8 shadow-2xl"><div className="mb-8 flex h-12 w-12 items-center justify-center rounded-xl bg-[#4169E1] shadow-[0_0_30px_rgba(65,105,225,.45)]"><LogIn/></div><p className="font-mono text-xs text-[#6C8EFF]">BAWERK / ADMIN</p><h1 className="mt-3 text-3xl font-semibold">Bem-vindo de volta</h1><p className="mt-2 text-sm text-zinc-500">Acesse contatos, métricas e usuários.</p><input value={password} onChange={e=>setPassword(e.target.value)} type="password" placeholder="Senha administrativa" className="mt-7 w-full rounded-xl border border-white/10 bg-black/30 px-4 py-3 outline-none focus:border-[#4169E1]"/><button className="mt-4 w-full rounded-xl bg-[#4169E1] px-4 py-3 font-medium transition hover:bg-[#5579e7]">Entrar</button>{error&&<p className="mt-4 text-sm text-red-400">{error}</p>}</form></div>}
function Sidebar({view,setView,unread,open}:{view:View;setView:(v:View)=>void;unread:number;open:boolean}){const items:[View,typeof LayoutDashboard,string][]=[["overview",LayoutDashboard,"Visão geral"],["messages",Inbox,"Mensagens"],["users",Users,"Usuários"],["settings",Settings,"Configurações"]];return <aside className={`${open?"flex":"hidden"} fixed inset-y-2 left-2 z-40 w-64 flex-col rounded-l-[26px] border-r border-white/10 bg-[#080a0e] p-5 lg:static lg:flex lg:w-64`}><div className="flex items-center gap-3 border-b border-white/10 pb-6"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#4169E1] font-mono font-bold shadow-[0_0_22px_rgba(65,105,225,.45)]">BW</div><div><p className="font-semibold">BAWERK</p><p className="text-[11px] text-zinc-500">Painel administrativo</p></div></div><nav className="mt-7 space-y-2">{items.map(([id,Icon,label])=><button key={id} onClick={()=>setView(id)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-sm transition ${view===id?"bg-gradient-to-r from-[#4169E1] to-[#2b54cf] text-white shadow-[0_8px_24px_rgba(65,105,225,.22)]":"text-zinc-500 hover:bg-white/5 hover:text-white"}`}><Icon className="h-4 w-4"/><span>{label}</span>{id==="messages"&&unread>0&&<b className="ml-auto rounded-full bg-white/15 px-2 py-0.5 text-[10px]">{unread}</b>}</button>)}</nav><div className="mt-auto rounded-2xl border border-white/10 bg-white/[.025] p-4"><p className="text-xs text-zinc-500">Sistema</p><div className="mt-2 flex items-center gap-2 text-sm"><i className="h-2 w-2 rounded-full bg-emerald-400"/>Online e protegido</div></div></aside>}
function Topbar({query,setQuery,menu,unread}:{query:string;setQuery:(v:string)=>void;menu:()=>void;unread:number}){return <header className="flex h-20 items-center gap-3 border-b border-white/10 px-4 sm:px-7"><button onClick={menu} className="rounded-lg p-2 hover:bg-white/5 lg:hidden"><Menu/></button><label className="flex max-w-xl flex-1 items-center gap-3 rounded-xl border border-white/5 bg-[#11141b] px-4 py-3"><Search className="h-4 w-4 text-zinc-500"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar mensagens e clientes" className="min-w-0 flex-1 bg-transparent text-sm outline-none"/></label><button className="relative ml-auto rounded-xl border border-white/5 bg-[#11141b] p-3"><Bell className="h-4 w-4"/>{unread>0&&<i className="absolute right-2 top-2 h-2 w-2 rounded-full bg-red-500"/>}</button><div className="hidden items-center gap-3 sm:flex"><div className="flex h-10 w-10 items-center justify-center rounded-full bg-[#4169E1]/20 font-semibold text-[#8ca5ff]">A</div><div><p className="text-sm">Administrador</p><p className="text-[11px] text-zinc-500">BAWERK Solutions</p></div></div></header>}

function Overview({analytics,leads,unread,important,openMessages}:{analytics:TrafficOverview;leads:Lead[];unread:number;important:number;openMessages:()=>void}){return <><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm text-[#6C8EFF]">Visão geral</p><h1 className="mt-1 text-3xl font-semibold">Dashboard</h1><p className="mt-2 text-sm text-zinc-500">Acompanhe o desempenho do site e os novos contatos.</p></div><p className="rounded-xl border border-white/10 bg-white/[.025] px-4 py-2 text-xs text-zinc-400">Últimos 30 dias</p></div><div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric title="Acessos" value={analytics.total} icon={Eye} note={`${analytics.today} hoje`}/><Metric title="Visitantes" value={analytics.uniqueSessions} icon={BarChart3} note="sessões únicas"/><Metric title="Novas mensagens" value={unread} icon={Mail} note={`${leads.length} no total`}/><Metric title="Importantes" value={important} icon={Star} note="marcadas por você"/></div><div className="mt-5 grid gap-5 xl:grid-cols-[1.7fr_1fr]"><TrafficChart hours={analytics.hours}/><Ranking title="Origem dos acessos" rows={analytics.sources}/></div><div className="mt-5 grid gap-5 xl:grid-cols-[1.15fr_1fr]"><Recent leads={leads.slice(0,5)} open={openMessages}/><div className="grid gap-5 sm:grid-cols-2"><Ranking title="Páginas mais acessadas" rows={analytics.pages}/><Ranking title="Dispositivos" rows={analytics.devices}/></div></div></>}
function Metric({title,value,icon:Icon,note}:{title:string;value:number;icon:typeof Eye;note:string}){return <div className="rounded-2xl border border-white/10 bg-[#0e1118] p-5 transition hover:border-[#4169E1]/50"><div className="flex items-center justify-between"><p className="text-sm text-zinc-400">{title}</p><span className="rounded-xl bg-[#4169E1]/15 p-2 text-[#6C8EFF]"><Icon className="h-4 w-4"/></span></div><p className="mt-5 text-3xl font-semibold">{value.toLocaleString("pt-BR")}</p><p className="mt-2 text-xs text-zinc-600">{note}</p></div>}
function TrafficChart({hours}:{hours:{label:string;value:number}[]}){const max=Math.max(1,...hours.map(x=>x.value));const points=hours.map((x,i)=>`${(i/(Math.max(1,hours.length-1)))*100},${92-(x.value/max)*72}`).join(" ");return <div className="rounded-2xl border border-white/10 bg-[#0e1118] p-5 sm:p-6"><div><h2 className="font-medium">Tráfego por horário</h2><p className="mt-1 text-xs text-zinc-500">Acessos registrados hoje</p></div><div className="mt-7 h-64 overflow-hidden rounded-xl bg-[linear-gradient(rgba(255,255,255,.035)_1px,transparent_1px)] bg-[size:100%_25%]"><svg viewBox="0 0 100 100" preserveAspectRatio="none" className="h-full w-full"><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#4169E1" stopOpacity=".65"/><stop offset="1" stopColor="#4169E1" stopOpacity="0"/></linearGradient></defs><polygon points={`0,100 ${points} 100,100`} fill="url(#area)"/><polyline points={points} fill="none" stroke="#6C8EFF" strokeWidth="1.1" vectorEffect="non-scaling-stroke"/></svg></div><div className="mt-3 flex justify-between text-[10px] text-zinc-600"><span>00:00</span><span>06:00</span><span>12:00</span><span>18:00</span><span>23:00</span></div></div>}
function Ranking({title,rows}:{title:string;rows:{label:string;value:number}[]}){const max=Math.max(1,...rows.map(x=>x.value));return <div className="rounded-2xl border border-white/10 bg-[#0e1118] p-5"><h2 className="font-medium">{title}</h2><div className="mt-5 space-y-4">{rows.length?rows.map(x=><div key={x.label}><div className="flex justify-between gap-3 text-xs"><span className="truncate text-zinc-400">{x.label}</span><b>{x.value}</b></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-white/5"><div className="h-full rounded-full bg-[#4169E1]" style={{width:`${Math.max(8,x.value/max*100)}%`}}/></div></div>):<p className="py-8 text-center text-xs text-zinc-600">Os dados aparecerão após novos acessos.</p>}</div></div>}
function Recent({leads,open}:{leads:Lead[];open:()=>void}){return <div className="rounded-2xl border border-white/10 bg-[#0e1118] p-5"><div className="flex items-center justify-between"><h2 className="font-medium">Contatos recentes</h2><button onClick={open} className="text-xs text-[#6C8EFF]">Ver todos</button></div><div className="mt-4 divide-y divide-white/5">{leads.map(x=><div className="flex items-center gap-3 py-3" key={x.id}><Avatar name={x.name}/><div className="min-w-0"><p className="truncate text-sm">{x.name}</p><p className="truncate text-xs text-zinc-500">{x.service||x.email}</p></div><Status value={x.status}/></div>)}{!leads.length&&<p className="py-8 text-center text-sm text-zinc-600">Nenhum contato ainda.</p>}</div></div>}

function Messages({leads,selected,setSelected,updateLead,important,later}:{leads:Lead[];selected:Lead|null;setSelected:(x:Lead|null)=>void;updateLead:(id:number,d:{status?:string;important?:boolean})=>void;important:number;later:number}){return <><div><p className="text-sm text-[#6C8EFF]">Central de contatos</p><h1 className="mt-1 text-3xl font-semibold">Mensagens</h1></div><div className="mt-6 flex flex-wrap gap-3"><Pill icon={Inbox} text={`${leads.length} mensagens`}/><Pill icon={Star} text={`${important} importantes`}/><Pill icon={Bookmark} text={`${later} para ver depois`}/></div><div className="mt-6 overflow-hidden rounded-2xl border border-white/10 bg-[#0e1118]"><div className="hidden grid-cols-[36px_1fr_1fr_150px_110px] gap-4 border-b border-white/10 px-5 py-4 text-xs text-zinc-600 sm:grid"><span/><span>Cliente</span><span>Assunto</span><span>Status</span><span>Data</span></div>{leads.map(x=><button key={x.id} onClick={()=>setSelected(x)} className={`grid w-full grid-cols-[32px_1fr_auto] items-center gap-3 border-b border-white/5 px-4 py-4 text-left transition hover:bg-white/[.025] sm:grid-cols-[36px_1fr_1fr_150px_110px] sm:px-5 ${x.status==="new"?"bg-[#4169E1]/[.035]":""}`}><Star onClick={e=>{e.stopPropagation();updateLead(x.id,{important:!x.important})}} className={`h-4 w-4 ${x.important?"fill-yellow-400 text-yellow-400":"text-zinc-700"}`}/><div className="min-w-0"><p className="truncate text-sm font-medium">{x.name}</p><p className="truncate text-xs text-zinc-600">{x.email}</p></div><div className="hidden min-w-0 sm:block"><p className="truncate text-sm text-zinc-400">{x.service||"Novo contato"}</p><p className="truncate text-xs text-zinc-600">{x.message}</p></div><Status value={x.status}/><span className="hidden text-xs text-zinc-600 sm:block">{new Date(x.created_at).toLocaleDateString("pt-BR")}</span></button>)}{!leads.length&&<p className="p-12 text-center text-zinc-600">Nenhuma mensagem encontrada.</p>}</div></>}
function MessageDrawer({lead,close,update}:{lead:Lead;close:()=>void;update:(id:number,d:{status?:string;important?:boolean})=>void}){return <div className="fixed inset-0 z-50 flex justify-end bg-black/70 backdrop-blur-sm" onClick={close}><article onClick={e=>e.stopPropagation()} className="h-full w-full max-w-2xl overflow-y-auto border-l border-white/10 bg-[#0b0e14] p-6 sm:p-9"><div className="flex items-center justify-between"><button onClick={close} className="text-sm text-zinc-500">Fechar</button><button onClick={()=>update(lead.id,{important:!lead.important})} className={`rounded-xl border p-3 ${lead.important?"border-yellow-400/30 bg-yellow-400/10 text-yellow-400":"border-white/10 text-zinc-500"}`}><Star className={`h-4 w-4 ${lead.important?"fill-current":""}`}/></button></div><div className="mt-9 flex items-center gap-4"><Avatar name={lead.name} big/><div><h2 className="text-2xl font-semibold">{lead.name}</h2><a href={`mailto:${lead.email}`} className="text-sm text-[#6C8EFF]">{lead.email}</a></div></div><div className="mt-8 grid gap-3 rounded-2xl border border-white/10 bg-white/[.02] p-5 text-sm sm:grid-cols-2"><p><span className="text-zinc-600">Telefone</span><br/>{lead.phone||"—"}</p><p><span className="text-zinc-600">Empresa</span><br/>{lead.company||"—"}</p><p><span className="text-zinc-600">Serviço</span><br/>{lead.service||"—"}</p><p><span className="text-zinc-600">Investimento</span><br/>{lead.budget||"—"}</p></div><div className="mt-7"><p className="text-xs uppercase tracking-widest text-zinc-600">Mensagem</p><p className="mt-4 whitespace-pre-wrap leading-7 text-zinc-300">{lead.message}</p></div><div className="mt-9 flex flex-wrap gap-3"><button onClick={()=>update(lead.id,{status:"responded"})} className="rounded-xl bg-[#4169E1] px-5 py-3 text-sm">Marcar como respondida</button><button onClick={()=>update(lead.id,{status:"later"})} className="rounded-xl border border-white/10 px-5 py-3 text-sm">Ver depois</button><button onClick={()=>update(lead.id,{status:"archived"})} className="rounded-xl border border-white/10 px-5 py-3 text-sm text-zinc-500">Arquivar</button></div></article></div>}

function UsersView({users,edit}:{users:AdminUser[];edit:(u:Partial<AdminUser>)=>void}){return <><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm text-[#6C8EFF]">Equipe</p><h1 className="mt-1 text-3xl font-semibold">Usuários</h1><p className="mt-2 text-sm text-zinc-500">Gerencie perfis, fotos, funções e status da equipe.</p></div><button onClick={()=>edit({status:"active",role:"Atendimento"})} className="rounded-xl bg-[#4169E1] px-5 py-3 text-sm">Adicionar usuário</button></div><div className="mt-7 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{users.map(u=><button onClick={()=>edit(u)} key={u.id} className="rounded-2xl border border-white/10 bg-[#0e1118] p-5 text-left transition hover:border-[#4169E1]/50"><div className="flex items-center gap-4">{u.avatar_url?<img src={u.avatar_url} alt="" className="h-14 w-14 rounded-full object-cover"/>:<Avatar name={u.name} big/>}<div className="min-w-0"><p className="truncate font-medium">{u.name}</p><p className="truncate text-xs text-zinc-500">{u.email}</p></div><i className={`ml-auto h-2 w-2 rounded-full ${u.status==="active"?"bg-emerald-400":"bg-zinc-600"}`}/></div><div className="mt-5 flex items-center justify-between border-t border-white/5 pt-4"><span className="rounded-lg bg-[#4169E1]/10 px-3 py-1 text-xs text-[#8ca5ff]">{u.role}</span><ChevronRight className="h-4 w-4 text-zinc-700"/></div></button>)}{!users.length&&<div className="col-span-full rounded-2xl border border-dashed border-white/10 p-14 text-center text-zinc-600">Nenhum usuário cadastrado. Adicione o primeiro perfil da equipe.</div>}</div></>}
function UserModal({data,setData,close,submit}:{data:Partial<AdminUser>;setData:(d:Partial<AdminUser>)=>void;close:()=>void;submit:(e:React.FormEvent)=>void}){return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/75 p-4 backdrop-blur-sm" onClick={close}><form onSubmit={submit} onClick={e=>e.stopPropagation()} className="w-full max-w-lg rounded-3xl border border-white/10 bg-[#0e1118] p-6 sm:p-8"><div className="flex items-center justify-between"><h2 className="text-xl font-semibold">{data.id?"Editar usuário":"Novo usuário"}</h2><button type="button" onClick={close}><X className="text-zinc-500"/></button></div><div className="mt-6 grid gap-4"><Field label="Nome" value={data.name||""} change={v=>setData({...data,name:v})}/><Field label="E-mail" value={data.email||""} change={v=>setData({...data,email:v})} type="email"/><Field label="URL da foto" value={data.avatar_url||""} change={v=>setData({...data,avatar_url:v})} required={false}/><label className="text-sm text-zinc-400">Função<select value={data.role||"Atendimento"} onChange={e=>setData({...data,role:e.target.value})} className="mt-2 w-full rounded-xl border border-white/10 bg-black/30 px-4 py-3 text-white"><option>Administrador</option><option>Atendimento</option><option>Comercial</option><option>Editor</option></select></label><label className="text-sm text-zinc-400">Status<select value={data.status||"active"} onChange={e=>setData({...data,status:e.target.value})} className="mt-2 w-full rounded-xl border border-white/10 bg-black/30 px-4 py-3 text-white"><option value="active">Ativo</option><option value="inactive">Inativo</option></select></label></div><button className="mt-6 w-full rounded-xl bg-[#4169E1] px-5 py-3">Salvar usuário</button><p className="mt-3 text-center text-[11px] text-zinc-600">Os perfis organizam a equipe. O login continua protegido pelas variáveis da Vercel.</p></form></div>}
function SettingsView(){return <div><p className="text-sm text-[#6C8EFF]">Sistema</p><h1 className="mt-1 text-3xl font-semibold">Configurações</h1><div className="mt-7 grid max-w-3xl gap-4"><div className="rounded-2xl border border-white/10 bg-[#0e1118] p-6"><h2 className="font-medium">Segurança administrativa</h2><p className="mt-2 text-sm leading-6 text-zinc-500">A senha e o segredo de sessão são administrados pelas variáveis ADMIN_PASSWORD e ADMIN_SECRET na Vercel.</p></div><div className="rounded-2xl border border-white/10 bg-[#0e1118] p-6"><h2 className="font-medium">Banco de dados</h2><p className="mt-2 text-sm leading-6 text-zinc-500">Contatos, acessos e perfis são armazenados com segurança no banco Neon conectado ao projeto.</p></div></div></div>}

function Avatar({name,big=false}:{name:string;big?:boolean}){return <span className={`flex shrink-0 items-center justify-center rounded-full bg-gradient-to-br from-[#4169E1] to-[#223b91] font-semibold ${big?"h-14 w-14 text-lg":"h-10 w-10 text-sm"}`}>{name.split(" ").slice(0,2).map(x=>x[0]).join("").toUpperCase()}</span>}
function Status({value}:{value:string}){const map:Record<string,[string,string]>={new:["Nova","bg-[#4169E1]/15 text-[#8ca5ff]"],read:["Lida","bg-white/5 text-zinc-400"],later:["Ver depois","bg-amber-400/10 text-amber-300"],responded:["Respondida","bg-emerald-400/10 text-emerald-300"],archived:["Arquivada","bg-zinc-800 text-zinc-500"]};const [label,style]=map[value]||map.read;return <span className={`ml-auto w-fit rounded-full px-2.5 py-1 text-[10px] ${style}`}>{label}</span>}
function Pill({icon:Icon,text}:{icon:typeof Inbox;text:string}){return <span className="flex items-center gap-2 rounded-xl border border-white/10 bg-white/[.025] px-4 py-2 text-xs text-zinc-400"><Icon className="h-3.5 w-3.5 text-[#6C8EFF]"/>{text}</span>}
function Field({label,value,change,type="text",required=true}:{label:string;value:string;change:(v:string)=>void;type?:string;required?:boolean}){return <label className="text-sm text-zinc-400">{label}<input required={required} type={type} value={value} onChange={e=>change(e.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-black/30 px-4 py-3 text-white outline-none focus:border-[#4169E1]"/></label>}
