import { neon } from "@neondatabase/serverless"
export type Lead={id:number;name:string;email:string;phone:string|null;company:string|null;service:string|null;budget:string|null;message:string;status:string;important:boolean;created_at:string;updated_at:string}
export type AdminUser={id:number;name:string;email:string;role:string;avatar_url:string|null;status:string;created_at:string}
export type TrafficOverview={total:number;today:number;uniqueSessions:number;sources:{label:string;value:number}[];pages:{label:string;value:number}[];devices:{label:string;value:number}[];hours:{label:string;value:number}[]}
function sql(){const url=process.env.DATABASE_URL||process.env.POSTGRES_URL;if(!url)throw new Error("DATABASE_URL não configurada");return neon(url)}
export async function ensureTables(){const db=sql();await db`CREATE TABLE IF NOT EXISTS bawerk_leads (id SERIAL PRIMARY KEY,name TEXT NOT NULL,email TEXT NOT NULL,phone TEXT,company TEXT,service TEXT,budget TEXT,message TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'new',important BOOLEAN NOT NULL DEFAULT FALSE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`;await db`ALTER TABLE bawerk_leads ADD COLUMN IF NOT EXISTS important BOOLEAN NOT NULL DEFAULT FALSE`;await db`ALTER TABLE bawerk_leads ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()`;await db`CREATE TABLE IF NOT EXISTS bawerk_traffic (id BIGSERIAL PRIMARY KEY,path TEXT NOT NULL,source TEXT NOT NULL DEFAULT 'Direto',device TEXT NOT NULL DEFAULT 'Desktop',session_id TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`;await db`CREATE INDEX IF NOT EXISTS bawerk_traffic_created_idx ON bawerk_traffic(created_at DESC)`;await db`CREATE TABLE IF NOT EXISTS bawerk_admin_users (id SERIAL PRIMARY KEY,name TEXT NOT NULL,email TEXT NOT NULL UNIQUE,role TEXT NOT NULL DEFAULT 'Atendimento',avatar_url TEXT,status TEXT NOT NULL DEFAULT 'active',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`}
export async function createLead(data:Omit<Lead,"id"|"status"|"important"|"created_at"|"updated_at">){await ensureTables();const rows=await sql()`INSERT INTO bawerk_leads (name,email,phone,company,service,budget,message) VALUES (${data.name},${data.email},${data.phone},${data.company},${data.service},${data.budget},${data.message}) RETURNING id`;return rows[0]}
export async function listLeads(){await ensureTables();return await sql()`SELECT * FROM bawerk_leads ORDER BY important DESC,created_at DESC` as Lead[]}
export async function updateLead(id:number,data:{status?:string;important?:boolean}){await ensureTables();if(typeof data.important==="boolean")await sql()`UPDATE bawerk_leads SET important=${data.important},updated_at=NOW() WHERE id=${id}`;if(data.status)await sql()`UPDATE bawerk_leads SET status=${data.status},updated_at=NOW() WHERE id=${id}`}
export async function recordTraffic(data:{path:string;source:string;device:string;sessionId:string}){await ensureTables();await sql()`INSERT INTO bawerk_traffic(path,source,device,session_id) VALUES (${data.path},${data.source},${data.device},${data.sessionId})`}
export async function trafficOverview():Promise<TrafficOverview>{await ensureTables();const db=sql();const [totals,sources,pages,devices,hours]=await Promise.all([db`SELECT COUNT(*)::int total,COUNT(*) FILTER(WHERE created_at>=CURRENT_DATE)::int today,COUNT(DISTINCT session_id)::int unique_sessions FROM bawerk_traffic WHERE created_at>=NOW()-INTERVAL '30 days'`,db`SELECT source label,COUNT(*)::int value FROM bawerk_traffic WHERE created_at>=NOW()-INTERVAL '30 days' GROUP BY source ORDER BY value DESC LIMIT 6`,db`SELECT path label,COUNT(*)::int value FROM bawerk_traffic WHERE created_at>=NOW()-INTERVAL '30 days' GROUP BY path ORDER BY value DESC LIMIT 6`,db`SELECT device label,COUNT(*)::int value FROM bawerk_traffic WHERE created_at>=NOW()-INTERVAL '30 days' GROUP BY device ORDER BY value DESC`,db`SELECT TO_CHAR(h,'HH24:00') label,COALESCE(COUNT(t.id),0)::int value FROM generate_series(date_trunc('day',NOW()),date_trunc('day',NOW())+INTERVAL '23 hours',INTERVAL '1 hour') h LEFT JOIN bawerk_traffic t ON date_trunc('hour',t.created_at)=h GROUP BY h ORDER BY h`]);return{total:totals[0]?.total||0,today:totals[0]?.today||0,uniqueSessions:totals[0]?.unique_sessions||0,sources:sources as {label:string;value:number}[],pages:pages as {label:string;value:number}[],devices:devices as {label:string;value:number}[],hours:hours as {label:string;value:number}[]}}
export async function listAdminUsers(){await ensureTables();return await sql()`SELECT * FROM bawerk_admin_users ORDER BY created_at DESC` as AdminUser[]}
export async function saveAdminUser(data:{id?:number;name:string;email:string;role:string;avatarUrl?:string;status:string}){await ensureTables();if(data.id){await sql()`UPDATE bawerk_admin_users SET name=${data.name},email=${data.email},role=${data.role},avatar_url=${data.avatarUrl||null},status=${data.status} WHERE id=${data.id}`;return}await sql()`INSERT INTO bawerk_admin_users(name,email,role,avatar_url,status) VALUES(${data.name},${data.email},${data.role},${data.avatarUrl||null},${data.status})`}
