import { neon } from "@neondatabase/serverless"
export type Lead={id:number;name:string;email:string;phone:string|null;company:string|null;service:string|null;budget:string|null;message:string;status:string;important:boolean;created_at:string;updated_at:string}
export type AdminUser={id:number;name:string;email:string;role:string;avatar_url:string|null;status:string;created_at:string}
export type Client={id:number;name:string;company:string|null;email:string|null;phone:string|null;document:string|null;status:string;notes:string|null;created_at:string}
export type Charge={id:number;client_id:number;client_name:string;title:string;amount:number;recurrence:string;due_date:string;status:string;paid_at:string|null;notes:string|null;created_at:string}
export type AgendaEvent={id:number;client_id:number|null;client_name:string|null;title:string;event_type:string;starts_at:string;status:string;notes:string|null;created_at:string}
export type CrmOverview={clients:number;activeClients:number;mrr:number;pending:number;overdue:number;dueSoon:number;meetings:number}
export type TrafficOverview={total:number;today:number;uniqueSessions:number;sources:{label:string;value:number}[];pages:{label:string;value:number}[];devices:{label:string;value:number}[];hours:{label:string;value:number}[]}
function sql(){const url=process.env.DATABASE_URL||process.env.POSTGRES_URL;if(!url)throw new Error("DATABASE_URL não configurada");return neon(url)}
export async function ensureTables(){const db=sql();await db`CREATE TABLE IF NOT EXISTS bawerk_leads (id SERIAL PRIMARY KEY,name TEXT NOT NULL,email TEXT NOT NULL,phone TEXT,company TEXT,service TEXT,budget TEXT,message TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'new',important BOOLEAN NOT NULL DEFAULT FALSE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`;await db`ALTER TABLE bawerk_leads ADD COLUMN IF NOT EXISTS important BOOLEAN NOT NULL DEFAULT FALSE`;await db`ALTER TABLE bawerk_leads ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()`;await db`CREATE TABLE IF NOT EXISTS bawerk_traffic (id BIGSERIAL PRIMARY KEY,path TEXT NOT NULL,source TEXT NOT NULL DEFAULT 'Direto',device TEXT NOT NULL DEFAULT 'Desktop',session_id TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`;await db`CREATE INDEX IF NOT EXISTS bawerk_traffic_created_idx ON bawerk_traffic(created_at DESC)`;await db`CREATE TABLE IF NOT EXISTS bawerk_admin_users (id SERIAL PRIMARY KEY,name TEXT NOT NULL,email TEXT NOT NULL UNIQUE,role TEXT NOT NULL DEFAULT 'Atendimento',avatar_url TEXT,status TEXT NOT NULL DEFAULT 'active',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`;await db`CREATE TABLE IF NOT EXISTS bawerk_clients (id SERIAL PRIMARY KEY,name TEXT NOT NULL,company TEXT,email TEXT,phone TEXT,document TEXT,status TEXT NOT NULL DEFAULT 'active',notes TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`;await db`CREATE TABLE IF NOT EXISTS bawerk_charges (id SERIAL PRIMARY KEY,client_id INTEGER NOT NULL REFERENCES bawerk_clients(id) ON DELETE CASCADE,title TEXT NOT NULL,amount NUMERIC(12,2) NOT NULL DEFAULT 0,recurrence TEXT NOT NULL DEFAULT 'monthly',due_date DATE NOT NULL,status TEXT NOT NULL DEFAULT 'pending',paid_at TIMESTAMPTZ,notes TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`;await db`CREATE INDEX IF NOT EXISTS bawerk_charges_due_idx ON bawerk_charges(due_date,status)`;await db`CREATE TABLE IF NOT EXISTS bawerk_agenda (id SERIAL PRIMARY KEY,client_id INTEGER REFERENCES bawerk_clients(id) ON DELETE SET NULL,title TEXT NOT NULL,event_type TEXT NOT NULL DEFAULT 'meeting',starts_at TIMESTAMPTZ NOT NULL,status TEXT NOT NULL DEFAULT 'scheduled',notes TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`;await db`CREATE INDEX IF NOT EXISTS bawerk_agenda_start_idx ON bawerk_agenda(starts_at)`}
export async function createLead(data:Omit<Lead,"id"|"status"|"important"|"created_at"|"updated_at">){await ensureTables();const rows=await sql()`INSERT INTO bawerk_leads (name,email,phone,company,service,budget,message) VALUES (${data.name},${data.email},${data.phone},${data.company},${data.service},${data.budget},${data.message}) RETURNING id`;return rows[0]}
export async function listLeads(){await ensureTables();return await sql()`SELECT * FROM bawerk_leads ORDER BY important DESC,created_at DESC` as Lead[]}
export async function updateLead(id:number,data:{status?:string;important?:boolean}){await ensureTables();if(typeof data.important==="boolean")await sql()`UPDATE bawerk_leads SET important=${data.important},updated_at=NOW() WHERE id=${id}`;if(data.status)await sql()`UPDATE bawerk_leads SET status=${data.status},updated_at=NOW() WHERE id=${id}`}
export async function recordTraffic(data:{path:string;source:string;device:string;sessionId:string}){await ensureTables();await sql()`INSERT INTO bawerk_traffic(path,source,device,session_id) VALUES (${data.path},${data.source},${data.device},${data.sessionId})`}
export async function trafficOverview():Promise<TrafficOverview>{await ensureTables();const db=sql();const [totals,sources,pages,devices,hours]=await Promise.all([db`SELECT COUNT(*)::int total,COUNT(*) FILTER(WHERE created_at>=CURRENT_DATE)::int today,COUNT(DISTINCT session_id)::int unique_sessions FROM bawerk_traffic WHERE created_at>=NOW()-INTERVAL '30 days'`,db`SELECT source label,COUNT(*)::int value FROM bawerk_traffic WHERE created_at>=NOW()-INTERVAL '30 days' GROUP BY source ORDER BY value DESC LIMIT 6`,db`SELECT path label,COUNT(*)::int value FROM bawerk_traffic WHERE created_at>=NOW()-INTERVAL '30 days' GROUP BY path ORDER BY value DESC LIMIT 6`,db`SELECT device label,COUNT(*)::int value FROM bawerk_traffic WHERE created_at>=NOW()-INTERVAL '30 days' GROUP BY device ORDER BY value DESC`,db`SELECT TO_CHAR(h,'HH24:00') label,COALESCE(COUNT(t.id),0)::int value FROM generate_series(date_trunc('day',NOW()),date_trunc('day',NOW())+INTERVAL '23 hours',INTERVAL '1 hour') h LEFT JOIN bawerk_traffic t ON date_trunc('hour',t.created_at)=h GROUP BY h ORDER BY h`]);return{total:totals[0]?.total||0,today:totals[0]?.today||0,uniqueSessions:totals[0]?.unique_sessions||0,sources:sources as {label:string;value:number}[],pages:pages as {label:string;value:number}[],devices:devices as {label:string;value:number}[],hours:hours as {label:string;value:number}[]}}
export async function listAdminUsers(){await ensureTables();return await sql()`SELECT * FROM bawerk_admin_users ORDER BY created_at DESC` as AdminUser[]}
export async function saveAdminUser(data:{id?:number;name:string;email:string;role:string;avatarUrl?:string;status:string}){await ensureTables();if(data.id){await sql()`UPDATE bawerk_admin_users SET name=${data.name},email=${data.email},role=${data.role},avatar_url=${data.avatarUrl||null},status=${data.status} WHERE id=${data.id}`;return}await sql()`INSERT INTO bawerk_admin_users(name,email,role,avatar_url,status) VALUES(${data.name},${data.email},${data.role},${data.avatarUrl||null},${data.status})`}
export async function listClients(){await ensureTables();return await sql()`SELECT * FROM bawerk_clients ORDER BY status='active' DESC,name` as Client[]}
export async function saveClient(d:{id?:number;name:string;company?:string;email?:string;phone?:string;document?:string;status:string;notes?:string}){await ensureTables();const db=sql();if(d.id)return void await db`UPDATE bawerk_clients SET name=${d.name},company=${d.company||null},email=${d.email||null},phone=${d.phone||null},document=${d.document||null},status=${d.status},notes=${d.notes||null} WHERE id=${d.id}`;await db`INSERT INTO bawerk_clients(name,company,email,phone,document,status,notes) VALUES(${d.name},${d.company||null},${d.email||null},${d.phone||null},${d.document||null},${d.status},${d.notes||null})`}
export async function listCharges(){await ensureTables();return await sql()`SELECT c.*,cl.name client_name FROM bawerk_charges c JOIN bawerk_clients cl ON cl.id=c.client_id ORDER BY CASE c.status WHEN 'overdue' THEN 0 WHEN 'pending' THEN 1 ELSE 2 END,c.due_date` as Charge[]}
export async function saveCharge(d:{id?:number;clientId:number;title:string;amount:number;recurrence:string;dueDate:string;status:string;notes?:string}){await ensureTables();const db=sql();if(d.id)return void await db`UPDATE bawerk_charges SET client_id=${d.clientId},title=${d.title},amount=${d.amount},recurrence=${d.recurrence},due_date=${d.dueDate},status=${d.status},paid_at=CASE WHEN ${d.status}='paid' THEN COALESCE(paid_at,NOW()) ELSE NULL END,notes=${d.notes||null} WHERE id=${d.id}`;await db`INSERT INTO bawerk_charges(client_id,title,amount,recurrence,due_date,status,paid_at,notes) VALUES(${d.clientId},${d.title},${d.amount},${d.recurrence},${d.dueDate},${d.status},CASE WHEN ${d.status}='paid' THEN NOW() ELSE NULL END,${d.notes||null})`}
export async function listAgenda(){await ensureTables();return await sql()`SELECT a.*,cl.name client_name FROM bawerk_agenda a LEFT JOIN bawerk_clients cl ON cl.id=a.client_id ORDER BY a.starts_at` as AgendaEvent[]}
export async function saveAgenda(d:{id?:number;clientId?:number;title:string;eventType:string;startsAt:string;status:string;notes?:string}){await ensureTables();const db=sql();if(d.id)return void await db`UPDATE bawerk_agenda SET client_id=${d.clientId||null},title=${d.title},event_type=${d.eventType},starts_at=${d.startsAt},status=${d.status},notes=${d.notes||null} WHERE id=${d.id}`;await db`INSERT INTO bawerk_agenda(client_id,title,event_type,starts_at,status,notes) VALUES(${d.clientId||null},${d.title},${d.eventType},${d.startsAt},${d.status},${d.notes||null})`}
export async function crmOverview():Promise<CrmOverview>{await ensureTables();const [c,f,a]=await Promise.all([sql()`SELECT COUNT(*)::int clients,COUNT(*) FILTER(WHERE status='active')::int active FROM bawerk_clients`,sql()`SELECT COALESCE(SUM(amount) FILTER(WHERE recurrence='monthly' AND status!='cancelled'),0)::float mrr,COALESCE(SUM(amount) FILTER(WHERE status IN ('pending','overdue')),0)::float pending,COUNT(*) FILTER(WHERE status='overdue' OR (status='pending' AND due_date<CURRENT_DATE))::int overdue,COUNT(*) FILTER(WHERE status='pending' AND due_date BETWEEN CURRENT_DATE AND CURRENT_DATE+7)::int due_soon FROM bawerk_charges`,sql()`SELECT COUNT(*)::int meetings FROM bawerk_agenda WHERE status='scheduled' AND starts_at>=NOW() AND starts_at<NOW()+INTERVAL '7 days'`]);return{clients:c[0].clients,activeClients:c[0].active,mrr:f[0].mrr,pending:f[0].pending,overdue:f[0].overdue,dueSoon:f[0].due_soon,meetings:a[0].meetings}}
