export type Language = "pt-BR" | "en"

const pt = {
  seo: { title: "BAWERK SOLUTIONS | Software, websites, design e crescimento", description: "Transformamos ideias em realidade digital por meio do desenvolvimento de software, websites, experiências digitais e estratégias de crescimento." },
  nav: { services: "Serviços", projects: "Projetos", about: "Sobre", faq: "Perguntas frequentes", contact: "Contato", cta: "Fale conosco", home: "Página inicial da BAWERK SOLUTIONS", language: "Selecionar idioma" },
  hero: { title: "Você pode ir além do que imagina.", accent: "Nós transformamos ideias em realidade digital.", body: "Desenvolvemos software, websites, experiências digitais e estratégias de crescimento para levar sua marca mais longe.", cta: "Comece seu projeto", highlights: [{ value: "Software", label: "Sob medida", desc: "Soluções criadas para os seus objetivos" }, { value: "Design", label: "Com propósito", desc: "Experiências claras, bonitas e funcionais" }, { value: "Crescimento", label: "Estratégico", desc: "Campanhas focadas no seu negócio" }] },
  services: { eyebrow: "Serviços", title: "Tecnologia, design e crescimento em um só lugar.", body: "Da primeira ideia à evolução contínua, unimos estratégia e execução para construir presenças digitais relevantes.", items: [
    { title: "Desenvolvimento de software personalizado", body: "Sistemas digitais sob medida, planejados para os processos e desafios do seu negócio.", cta: "Conheça nossa abordagem" },
    { title: "Websites, landing pages e páginas de captura", body: "Páginas rápidas, responsivas e orientadas à experiência e à conversão.", cta: "Crie sua presença digital" },
    { title: "Design de UI e UX e identidade visual", body: "Interfaces intuitivas e identidades consistentes que expressam o valor da sua marca.", cta: "Fortaleça sua marca" },
    { title: "Temas para Shopify e TrayCommerce", body: "Experiências de comércio eletrônico personalizadas para apresentar e vender melhor.", cta: "Evolua sua loja" },
    { title: "Gestão de tráfego pago", body: "Planejamento, acompanhamento e otimização de mídia para alcançar o público certo.", cta: "Amplie seu alcance" },
    { title: "Google Ads e Meta Ads", body: "Campanhas estruturadas nas principais plataformas de anúncios para apoiar seu crescimento.", cta: "Planeje suas campanhas" },
  ]},
  process: { title: "Ideia, estratégia e execução.", subtitle: "Uma parceria próxima em cada etapa do seu projeto.", cards: [{ title: "Entender antes de criar", body: "Conhecemos seus objetivos e seu contexto para definir a solução certa." }, { title: "Design com clareza", body: "Organizamos conteúdo e interação para criar uma experiência simples e coerente." }, { title: "Construção que evolui", body: "Desenvolvemos soluções responsivas, sólidas e prontas para acompanhar seu negócio." }] },
  projects: { title: "Projetos que transformam ideias em experiências.", body: "Conheça marcas que ganharam presença digital com a BAWERK SOLUTIONS.", cta: "Falar sobre meu projeto", label: "Projeto", items: [{ name: "Ospe Floor", type: "Experiência digital" }, { name: "Linara Decorações", type: "Website e identidade digital" }, { name: "DINATOP Decorações", type: "Website e presença digital" }] },
  about: { title: "Soluções digitais para ir além.", body: "A BAWERK SOLUTIONS transforma ideias em realidade digital por meio do desenvolvimento de software, websites, experiências digitais e estratégias de crescimento.", result: "Resultado", resultBody: "Tecnologia e criatividade aplicadas aos objetivos reais de cada negócio.", details: "Estratégia alinhada · Design responsivo · Desenvolvimento personalizado · Evolução contínua" },
  faq: { title: "Perguntas frequentes", items: [{ q: "Que tipos de projeto a BAWERK SOLUTIONS desenvolve?", a: "Criamos software personalizado, websites, landing pages, identidades visuais, interfaces e temas para Shopify e TrayCommerce, além de estratégias de mídia paga." }, { q: "Como posso solicitar uma proposta?", a: "Entre em contato pelo formulário ou pelo WhatsApp e conte brevemente sobre seus objetivos. Nossa equipe dará continuidade à conversa." }, { q: "Os projetos funcionam em celular e computador?", a: "Sim. Planejamos e desenvolvemos experiências responsivas para diferentes tamanhos de tela." }] },
  contact: { title: "Vamos transformar sua ideia em realidade?", subtitle: "Conte sobre o seu projeto", name: "Nome", email: "E-mail", message: "Como podemos ajudar?", send: "Enviar pelo WhatsApp", address: "Endereço", phone: "Telefone", social: "Redes sociais" },
  footer: { services: "Serviços", company: "Empresa", connect: "Contato", rights: "Todos os direitos reservados.", links: ["Software personalizado", "Websites e landing pages", "UI, UX e identidade visual", "Comércio eletrônico", "Tráfego pago"], companyLinks: ["Sobre", "Projetos", "Perguntas frequentes"] },
} as const

const en = {
  seo: { title: "BAWERK SOLUTIONS | Software, websites, design, and growth", description: "We turn ideas into digital reality through software development, websites, digital experiences, and growth strategies." },
  nav: { services: "Services", projects: "Projects", about: "About", faq: "FAQ", contact: "Contact", cta: "Contact us", home: "BAWERK SOLUTIONS home page", language: "Select language" },
  hero: { title: "You can go beyond what you imagine.", accent: "We turn ideas into digital reality.", body: "We develop software, websites, digital experiences, and growth strategies to take your brand further.", cta: "Start your project", highlights: [{ value: "Software", label: "Tailor-made", desc: "Solutions created for your goals" }, { value: "Design", label: "With purpose", desc: "Clear, beautiful, and functional experiences" }, { value: "Growth", label: "Strategic", desc: "Campaigns focused on your business" }] },
  services: { eyebrow: "Services", title: "Technology, design, and growth in one place.", body: "From the first idea to continuous evolution, we combine strategy and execution to build relevant digital presences.", items: [
    { title: "Custom software development", body: "Tailor-made digital systems designed for your business processes and challenges.", cta: "Discover our approach" },
    { title: "Websites, landing pages, and lead capture pages", body: "Fast, responsive pages focused on experience and conversion.", cta: "Create your digital presence" },
    { title: "UI and UX design and visual identity", body: "Intuitive interfaces and consistent identities that express your brand's value.", cta: "Strengthen your brand" },
    { title: "Themes for Shopify and TrayCommerce", body: "Customized e-commerce experiences to showcase and sell better.", cta: "Evolve your store" },
    { title: "Paid traffic management", body: "Media planning, monitoring, and optimization to reach the right audience.", cta: "Expand your reach" },
    { title: "Google Ads and Meta Ads", body: "Structured campaigns on leading advertising platforms to support your growth.", cta: "Plan your campaigns" },
  ]},
  process: { title: "Idea, strategy, and execution.", subtitle: "A close partnership at every stage of your project.", cards: [{ title: "Understand before creating", body: "We learn about your goals and context to define the right solution." }, { title: "Design with clarity", body: "We organize content and interaction to create a simple, consistent experience." }, { title: "Built to evolve", body: "We develop responsive, solid solutions ready to grow with your business." }] },
  projects: { title: "Projects that turn ideas into experiences.", body: "Meet brands that built their digital presence with BAWERK SOLUTIONS.", cta: "Discuss my project", label: "Project", items: [{ name: "Ospe Floor", type: "Digital experience" }, { name: "Linara Decorações", type: "Website and digital identity" }, { name: "DINATOP Decorações", type: "Website and digital presence" }] },
  about: { title: "Digital solutions to go further.", body: "BAWERK SOLUTIONS turns ideas into digital reality through software development, websites, digital experiences, and growth strategies.", result: "Outcome", resultBody: "Technology and creativity applied to each business's real goals.", details: "Aligned strategy · Responsive design · Custom development · Continuous evolution" },
  faq: { title: "Frequently asked questions", items: [{ q: "What types of projects does BAWERK SOLUTIONS develop?", a: "We create custom software, websites, landing pages, visual identities, interfaces, and themes for Shopify and TrayCommerce, as well as paid media strategies." }, { q: "How can I request a proposal?", a: "Contact us through the form or WhatsApp and briefly describe your goals. Our team will continue the conversation." }, { q: "Do projects work on mobile and desktop?", a: "Yes. We plan and develop responsive experiences for different screen sizes." }] },
  contact: { title: "Shall we turn your idea into reality?", subtitle: "Tell us about your project", name: "Name", email: "Email", message: "How can we help?", send: "Send via WhatsApp", address: "Address", phone: "Phone", social: "Social media" },
  footer: { services: "Services", company: "Company", connect: "Contact", rights: "All rights reserved.", links: ["Custom software", "Websites and landing pages", "UI, UX, and visual identity", "E-commerce", "Paid traffic"], companyLinks: ["About", "Projects", "Frequently asked questions"] },
}

export const translations = { "pt-BR": pt, en }
export type Translation = (typeof translations)[Language]
