export type Language = "pt-BR" | "en"

export const translations = {
  "pt-BR": {
    seo: { title: "BAWERK SOLUTIONS | Software, APIs e experiências digitais", description: "A Bawerk Solutions desenvolve softwares, websites, APIs personalizadas, integrações, automações e experiências digitais criadas para cada empresa." },
    common: { online: "Online", demo: "Demonstração", illustrative: "Dados demonstrativos", menu: "Abrir menu", close: "Fechar menu", language: "Selecionar idioma", learn: "Saiba mais", projectFlow: "Fluxo do projeto", integrationMap: "Mapa de integração", service: "Serviço", build: "construção / responsiva / pronta", project: "Projeto" },
    nav: { platform: "Plataforma", services: "Serviços", api: "APIs", projects: "Projetos", process: "Processo", faq: "FAQ", contact: "Contato", cta: "Falar com a Bawerk", home: "Página inicial da BAWERK SOLUTIONS" },
    hero: { title: "VOCÊ PODE IR ALÉM DO QUE IMAGINA.", accent: "A BAWERK TRANSFORMA IDEIAS EM REALIDADE DIGITAL.", body: "Desenvolvimento de software, websites, APIs personalizadas, integrações e experiências digitais criadas para as necessidades de cada empresa.", cards: [{ code: "UI/UX", title: "Design de interfaces", body: "Experiências digitais atraentes, intuitivas e fáceis de utilizar." }, { code: "WEB", title: "Sites e sistemas", body: "Projetos personalizados, responsivos e preparados para diferentes dispositivos." }, { code: "API", title: "APIs e integrações", body: "Conexão de sistemas, dados e processos por meio de soluções personalizadas." }] },
    tech: { eyebrow: "Projeto em execução", title: "DA IDEIA À SOLUÇÃO, CADA ETAPA CONECTADA.", body: "Uma visão demonstrativa do fluxo de trabalho da Bawerk, com decisões de produto, design e tecnologia organizadas em uma única jornada.", stages: ["Briefing recebido", "Necessidades analisadas", "Experiência planejada", "Arquitetura definida", "Desenvolvimento iniciado", "Integrações validadas", "Testes concluídos", "Solução entregue"], fields: ["escopo / definido", "experiência / responsiva", "arquitetura / validada"], log: "fluxo de projeto sincronizado" },
    services: { eyebrow: "O que criamos", title: "SOLUÇÕES DIGITAIS CRIADAS PARA O SEU NEGÓCIO.", body: "Estratégia, design e engenharia trabalhando juntos para resolver necessidades reais.", items: [{ title: "Design de UI e UX", body: "Criamos interfaces digitais atraentes, intuitivas e fáceis de utilizar. Cada elemento é planejado para oferecer uma experiência clara e agradável." }, { title: "Desenvolvimento de websites e soluções web", body: "Criamos sites institucionais, landing pages, páginas de captura, lojas virtuais, sistemas e soluções web responsivas." }, { title: "Tráfego pago", body: "Planejamos e administramos campanhas no Google Ads e Meta Ads para ampliar a visibilidade, atrair público qualificado e apoiar as vendas." }, { title: "Software personalizado", body: "Desenvolvemos sistemas sob medida para regras, necessidades e processos específicos de cada empresa." }, { title: "E-commerce", body: "Criamos experiências e temas personalizados para Shopify e TrayCommerce." }, { title: "Identidade visual", body: "Desenvolvemos elementos visuais consistentes para representar a marca em diferentes canais." }] },
    api: { eyebrow: "Integrações sob medida", title: "APIs QUE CONECTAM SISTEMAS, DADOS E PROCESSOS.", body: "Desenvolvemos APIs personalizadas para conectar plataformas, automatizar processos, organizar o fluxo de informações e permitir que diferentes sistemas trabalhem em conjunto.", cards: [{ title: "APIs personalizadas", body: "Desenvolvimento de APIs sob medida, planejadas conforme as regras, necessidades e objetivos de cada operação." }, { title: "Integração de sistemas", body: "Conexão entre sistemas internos, plataformas externas, CRMs, ERPs, bancos de dados, meios de pagamento e outras ferramentas." }, { title: "Automação de processos", body: "Automatização de tarefas repetitivas, consultas, cadastros, notificações e troca de informações entre sistemas." }], capabilitiesTitle: "Possibilidades sob avaliação técnica", capabilities: ["APIs REST", "Webhooks", "CRMs e ERPs", "Meios de pagamento", "WhatsApp", "E-commerce", "Bancos de dados", "Painéis administrativos", "Autenticação e acesso", "Documentação técnica", "Monitoramento e manutenção"], nodes: ["Sistema da empresa", "API BAWERK", "Validação", "Processamento", "Banco de dados", "Resposta confirmada"], response: "tempo ilustrativo: 128 ms", log: "POST /integration · payload demonstrativo · 200 OK" },
    process: { eyebrow: "Como trabalhamos", title: "CLAREZA EM TODAS AS ETAPAS.", steps: [{ n: "01", title: "Entender o projeto", body: "Compreender a essência, a visão, as necessidades e os objetivos." }, { n: "02", title: "Design e arquitetura", body: "Transformar informações em conceitos visuais e definir a estrutura técnica da solução." }, { n: "03", title: "Desenvolvimento e detalhes", body: "Implementar e refinar cada elemento em colaboração com o cliente." }, { n: "04", title: "Testes, finalização e entrega", body: "Validar o funcionamento e entregar a solução pronta para utilização." }] },
    projects: { eyebrow: "Projetos", title: "EXPERIÊNCIAS CRIADAS PARA MARCAS REAIS.", body: "Uma seleção de projetos desenvolvidos com foco em presença digital, clareza e identidade.", visit: "Visitar projeto", items: [{ name: "Ospe Floor", category: "Experiência digital", href: "" }, { name: "Linara Decorações", category: "Website e presença digital", href: "https://www.linaradecoracao.com.br" }, { name: "DINATOP Decorações", category: "Website e presença digital", href: "https://www.dinatopdecoracoes.com.br" }] },
    faq: { eyebrow: "Perguntas frequentes", title: "ANTES DE COMEÇARMOS.", items: [{ q: "Qual é o tempo médio de desenvolvimento?", a: "O prazo depende do escopo, da complexidade e das integrações. Depois da análise inicial, apresentamos uma estimativa adequada ao projeto." }, { q: "É possível desenvolver software personalizado?", a: "Sim. A solução é planejada conforme as regras e necessidades da empresa, após avaliação técnica." }, { q: "Vocês desenvolvem APIs personalizadas?", a: "Sim. Projetamos APIs de acordo com os objetivos, regras de negócio e requisitos técnicos de cada operação." }, { q: "É possível integrar sistemas que já utilizamos?", a: "Em muitos casos, sim. A viabilidade depende das APIs, permissões e recursos disponibilizados por cada sistema e deve ser analisada previamente." }, { q: "Vocês desenvolvem websites personalizados?", a: "Sim. Criamos websites responsivos alinhados à identidade, ao conteúdo e aos objetivos de cada empresa." }, { q: "Vocês criam landing pages?", a: "Sim. Desenvolvemos landing pages e páginas de captura planejadas para campanhas e objetivos específicos." }, { q: "Trabalham com Shopify e TrayCommerce?", a: "Criamos experiências e temas personalizados para essas plataformas, conforme a viabilidade e o escopo técnico." }, { q: "Vocês oferecem gestão de tráfego pago?", a: "Sim. Planejamos e acompanhamos campanhas em Google Ads e Meta Ads de acordo com os objetivos definidos." }] },
    footer: { title: "VAMOS TRANSFORMAR SUA IDEIA EM REALIDADE DIGITAL?", body: "Conte o que sua empresa precisa. A Bawerk Solutions prepara uma solução personalizada para o projeto.", cta: "Chamar no WhatsApp", description: "Desenvolvimento de software, APIs personalizadas, integrações, soluções web, design de interfaces e estratégias de crescimento digital.", navigate: "Navegação", solutions: "Soluções", social: "Canais", rights: "Todos os direitos reservados." }
  },
  en: {
    seo: { title: "BAWERK SOLUTIONS | Software, APIs, and digital experiences", description: "Bawerk Solutions develops software, websites, custom APIs, integrations, automations, and digital experiences tailored to each company’s needs." },
    common: { online: "Online", demo: "Demo", illustrative: "Demonstration data", menu: "Open menu", close: "Close menu", language: "Select language", learn: "Learn more", projectFlow: "Project flow", integrationMap: "Integration map", service: "Service", build: "build / responsive / ready", project: "Project" },
    nav: { platform: "Platform", services: "Services", api: "APIs", projects: "Projects", process: "Process", faq: "FAQ", contact: "Contact", cta: "Talk to Bawerk", home: "BAWERK SOLUTIONS home page" },
    hero: { title: "YOU CAN GO BEYOND WHAT YOU IMAGINE.", accent: "BAWERK TRANSFORMS IDEAS INTO DIGITAL REALITY.", body: "Software, websites, custom APIs, integrations, and digital experiences tailored to each company’s needs.", cards: [{ code: "UI/UX", title: "Interface design", body: "Attractive, intuitive, and easy-to-use digital experiences." }, { code: "WEB", title: "Websites and systems", body: "Custom, responsive projects prepared for different devices." }, { code: "API", title: "APIs and integrations", body: "Connecting systems, data, and processes through tailored solutions." }] },
    tech: { eyebrow: "Project in progress", title: "FROM IDEA TO SOLUTION, EVERY STEP CONNECTED.", body: "A demonstration of Bawerk’s workflow, organizing product, design, and technology decisions into one journey.", stages: ["Brief received", "Needs analyzed", "Experience planned", "Architecture defined", "Development started", "Integrations validated", "Tests completed", "Solution delivered"], fields: ["scope / defined", "experience / responsive", "architecture / validated"], log: "project workflow synchronized" },
    services: { eyebrow: "What we create", title: "DIGITAL SOLUTIONS BUILT FOR YOUR BUSINESS.", body: "Strategy, design, and engineering working together to address real needs.", items: [{ title: "UI and UX design", body: "We create attractive, intuitive, and easy-to-use digital interfaces. Every element is planned to provide a clear and pleasant experience." }, { title: "Website and web solution development", body: "We create institutional websites, landing pages, lead capture pages, online stores, systems, and responsive web solutions." }, { title: "Paid traffic", body: "We plan and manage Google Ads and Meta Ads campaigns to increase visibility, attract qualified audiences, and support sales." }, { title: "Custom software", body: "We develop systems tailored to each company’s specific rules, needs, and processes." }, { title: "E-commerce", body: "We create custom experiences and themes for Shopify and TrayCommerce." }, { title: "Visual identity", body: "We develop consistent visual elements to represent the brand across different channels." }] },
    api: { eyebrow: "Tailored integrations", title: "APIs THAT CONNECT SYSTEMS, DATA, AND PROCESSES.", body: "We develop custom APIs to connect platforms, automate processes, organize information flows, and enable different systems to work together.", cards: [{ title: "Custom APIs", body: "Tailored API development planned around each operation’s rules, needs, and goals." }, { title: "System integration", body: "Connections between internal systems, external platforms, CRMs, ERPs, databases, payment providers, and other tools." }, { title: "Process automation", body: "Automation of repetitive tasks, queries, registrations, notifications, and information exchange between systems." }], capabilitiesTitle: "Possibilities subject to technical assessment", capabilities: ["REST APIs", "Webhooks", "CRMs and ERPs", "Payment providers", "WhatsApp", "E-commerce", "Databases", "Admin dashboards", "Authentication and access", "Technical documentation", "Monitoring and maintenance"], nodes: ["Company system", "BAWERK API", "Validation", "Processing", "Database", "Response confirmed"], response: "illustrative time: 128 ms", log: "POST /integration · demonstration payload · 200 OK" },
    process: { eyebrow: "How we work", title: "CLARITY AT EVERY STAGE.", steps: [{ n: "01", title: "Understand the project", body: "Understand its essence, vision, needs, and goals." }, { n: "02", title: "Design and architecture", body: "Turn information into visual concepts and define the solution’s technical structure." }, { n: "03", title: "Development and details", body: "Implement and refine every element in collaboration with the client." }, { n: "04", title: "Testing, completion, and delivery", body: "Validate functionality and deliver the solution ready for use." }] },
    projects: { eyebrow: "Projects", title: "EXPERIENCES CREATED FOR REAL BRANDS.", body: "A selection of projects developed with a focus on digital presence, clarity, and identity.", visit: "Visit project", items: [{ name: "Ospe Floor", category: "Digital experience", href: "" }, { name: "Linara Decorações", category: "Website and digital presence", href: "https://www.linaradecoracao.com.br" }, { name: "DINATOP Decorações", category: "Website and digital presence", href: "https://www.dinatopdecoracoes.com.br" }] },
    faq: { eyebrow: "Frequently asked questions", title: "BEFORE WE BEGIN.", items: [{ q: "What is the average development time?", a: "Timing depends on scope, complexity, and integrations. After the initial assessment, we provide an estimate tailored to the project." }, { q: "Can you develop custom software?", a: "Yes. The solution is planned around the company’s rules and needs, following a technical assessment." }, { q: "Do you develop custom APIs?", a: "Yes. We design APIs according to each operation’s goals, business rules, and technical requirements." }, { q: "Can you integrate systems we already use?", a: "In many cases, yes. Feasibility depends on the APIs, permissions, and resources each system provides and must be assessed beforehand." }, { q: "Do you develop custom websites?", a: "Yes. We create responsive websites aligned with each company’s identity, content, and goals." }, { q: "Do you create landing pages?", a: "Yes. We develop landing and lead capture pages planned for specific campaigns and goals." }, { q: "Do you work with Shopify and TrayCommerce?", a: "We create custom experiences and themes for these platforms, subject to technical feasibility and scope." }, { q: "Do you offer paid traffic management?", a: "Yes. We plan and monitor campaigns on Google Ads and Meta Ads according to the defined goals." }] },
    footer: { title: "LET’S TURN YOUR IDEA INTO DIGITAL REALITY.", body: "Tell us what your company needs. Bawerk Solutions will prepare a tailored solution for your project.", cta: "Contact us on WhatsApp", description: "Software development, custom APIs, integrations, web solutions, interface design, and digital growth strategies.", navigate: "Navigation", solutions: "Solutions", social: "Channels", rights: "All rights reserved." }
  }
} as const
export type Translation = (typeof translations)[Language]
